### ISSUE TITLE
Change the core framework to use WP-CLI

### ISSUE THREAD

**Issue by donini** [donini/wordpress-automation#2]
As suggest @claudiosmweb, use the wp-cli brings several improvements to this "framework" concept, so it will be changed.

**Comment by donini** [comment]
Changes implemented in version 1.1.0

**Comment by claudiosanches** [comment]
Da hora, bem mais limpo assim sem ter que ter todas as pastas do WordPress e o banco de dados funciona até se não usar o prefixo como `wp_` :smile:
